apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: apps
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx-app
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
    app.kubernetes.io/instance: nginx-app
